const WORKERS_URL = "https://zaraz.lyrx.workers.dev";

const html = `<!DOCTYPE html>
<head>
<script>
const name = "Ivo";
const quote = "Give a man a gun and he can rob a bank, but give a man a bank, and he can rob the world.";
</script>
<script src="${WORKERS_URL}/script"></script>
</head>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;

function script(request) {
  const cookies = request.headers.get("Cookie");
  if (cookies.includes("name")) {
    return new Response(`console.log(document.cookies)`, {
      headers: {
        "content-type": "application/javascript",
      },
    });
  }

  return new Response(
    `fetch('${WORKERS_URL}', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({name, quote}),
})`,
    {
      headers: {
        "content-type": "application/javascript",
      },
    }
  );
}

async function handleRequest(request) {
  const { pathname } = new URL(request.url);

  if (request.method === "POST") {
    const response = new Response(
      JSON.stringify({ ip: request.headers.get("x-real-ip") })
    );
    const { name, quote } = JSON.parse(request.body);
    const latestExpires = new Date(
      new Date().getTime() + 60 * 60 * 1000 * 24
    ).toGMTString();
    response.headers.append(
      "set-cookie",
      `name=${name}; Expires=${latestExpires}`
    );
    response.headers.append(
      "set-cookie",
      `quote=${quote}; Expires=${latestExpires}`
    );

    return response;
  }

  if (pathname.startsWith("/script")) {
    return script(request);
  }

  return new Response(html, {
    headers: {
      "content-type": "text/html;charset=UTF-8",
    },
  });
}

addEventListener("fetch", (event) => {
  return event.respondWith(handleRequest(event.request));
});
